# Barriers 

In this notebook the barrier dataset is explored.

In [7]:
import pandas as pd
import geopandas as gpd
import fiona
from ipyfilechooser import FileChooser

In [8]:
# Select your file, for this notebook, the input is called:
# Humber_Barriers_03Mar2021.gpkg
fc = FileChooser()
display(fc)

FileChooser(path='/home/javad/Documents/codes/Tom', filename='', title='HTML(value='', layout=Layout(display='â€¦

In [9]:
# if for any reason this cell doesn't work try providing the path manually:
# Like this:
# br_df = gpd.read_file("codes/Tom/data/Humber_Barriers_03Mar2021.gpkg")

br_df = gpd.read_file(fc.selected)

AttributeError: 'NoneType' object has no attribute 'startswith'

In [ ]:
br_df

`Geopandas` only reads one layer! To fix this issue, find all the layers and read them separately.

In [10]:
# check the layers
for layername in fiona.listlayers('data/Humber_Barriers_03Mar2021.gpkg'):
    with fiona.open('data/Humber_Barriers_03Mar2021.gpkg', layer=layername) as src:
        print(layername, len(src))

PR_Humber_Dams_grand 1
PR_Humber_Dams_nhn 31
PR_Humber_Dams_nlprov 34
PR_Humber_Dams_npdp 1
PR_Humber_Falls_NHN 31
layer_styles 5

In [11]:
for layername in fiona.listlayers('data/Humber_Barriers_03Mar2021.gpkg'):
    geopkg = gpd.read_file(r'data/Humber_Barriers_03Mar2021.gpkg', layer=layername)
    df_name = layername.lower() + "_df"
    vars()[df_name] = geopkg
    print("The", df_name, " is creade")

/home/javad/anaconda3/envs/NHN/lib/python3.8/site-packages/geopandas/geodataframe.py:577: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
  for feature in features_lst:

The pr_humber_dams_grand_df  is creade
The pr_humber_dams_nhn_df  is creade
The pr_humber_dams_nlprov_df  is creade
The pr_humber_dams_npdp_df  is creade
The pr_humber_falls_nhn_df  is creade
The layer_styles_df  is creade

In [12]:
pr_humber_dams_grand_df

,GRAND_ID,RES_NAME,DAM_NAME,ALT_NAME,RIVER,ALT_RIVER,MAIN_BASIN,SUB_BASIN,NEAR_CITY,ALT_CITY,...,COMMENTS,URL,QUALITY,EDITOR,LONG_DD,LAT_DD,POLY_SRC,ID_GRanD,NL_Dam_Review_grand_Dam ID,geometry
0,2350,Grand Lake,Plain Diversion Dam,Main Diversion,Junction Brook,None,None,None,Deer Lake,None,...,None,None,3: Fair,McGill-BL,-57.261458,49.196212,CanVec,213,2350,POINT (-57.25639 49.19823)

### Check the size of each dataframe
the first number is the number or rows

In [13]:
pr_humber_dams_grand_df.shape, pr_humber_dams_nhn_df.shape,\
pr_humber_dams_nlprov_df.shape, pr_humber_dams_npdp_df.shape, pr_humber_falls_nhn_df.shape

((1, 61), (31, 25), (34, 22), (1, 38), (31, 21))

In [14]:
pr_humber_dams_grand_df.head()

,GRAND_ID,RES_NAME,DAM_NAME,ALT_NAME,RIVER,ALT_RIVER,MAIN_BASIN,SUB_BASIN,NEAR_CITY,ALT_CITY,...,COMMENTS,URL,QUALITY,EDITOR,LONG_DD,LAT_DD,POLY_SRC,ID_GRanD,NL_Dam_Review_grand_Dam ID,geometry
0,2350,Grand Lake,Plain Diversion Dam,Main Diversion,Junction Brook,None,None,None,Deer Lake,None,...,None,None,3: Fair,McGill-BL,-57.261458,49.196212,CanVec,213,2350,POINT (-57.25639 49.19823)

In [15]:
pr_humber_dams_grand_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 61 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   GRAND_ID                    1 non-null      int64
 1   RES_NAME                    1 non-null      object
 2   DAM_NAME                    1 non-null      object
 3   ALT_NAME                    1 non-null      object
 4   RIVER                       1 non-null      object
 5   ALT_RIVER                   0 non-null      object
 6   MAIN_BASIN                  0 non-null      object
 7   SUB_BASIN                   0 non-null      object
 8   NEAR_CITY                   1 non-null      object
 9   ALT_CITY                    0 non-null      object
 10  ADMIN_UNIT                  1 non-null      object
 11  SEC_ADMIN                   0 non-null      object
 12  COUNTRY                     1 non-null      object
 13  SEC_CNTRY                   0 non-null      object
 14  YEAR                        1 non-null      int64
 15  ALT_YEAR                    1 non-null      int64
 16  REM_YEAR                    1 non-null      int64
 17  DAM_HGT_M                   1 non-null      int64
 18  ALT_HGT_M                   1 non-null      int64
 19  DAM_LEN_M                   1 non-null      int64
 20  ALT_LEN_M                   1 non-null      int64
 21  AREA_SKM                    1 non-null      float64
 22  AREA_POLY                   1 non-null      float64
 23  AREA_REP                    1 non-null      float64
 24  AREA_MAX                    1 non-null      float64
 25  AREA_MIN                    1 non-null      float64
 26  CAP_MCM                     1 non-null      float64
 27  CAP_MAX                     1 non-null      float64
 28  CAP_REP                     1 non-null      float64
 29  CAP_MIN                     1 non-null      float64
 30  DEPTH_M                     1 non-null      float64
 31  DIS_AVG_LS                  1 non-null      int64
 32  DOR_PC                      1 non-null      float64
 33  ELEV_MASL                   1 non-null      int64
 34  CATCH_SKM                   1 non-null      int64
 35  CATCH_REP                   1 non-null      int64
 36  DATA_INFO                   0 non-null      object
 37  USE_IRRI                    0 non-null      object
 38  USE_ELEC                    1 non-null      object
 39  USE_SUPP                    0 non-null      object
 40  USE_FCON                    0 non-null      object
 41  USE_RECR                    0 non-null      object
 42  USE_NAVI                    0 non-null      object
 43  USE_FISH                    0 non-null      object
 44  USE_PCON                    0 non-null      object
 45  USE_LIVE                    0 non-null      object
 46  USE_OTHR                    0 non-null      object
 47  MAIN_USE                    1 non-null      object
 48  LAKE_CTRL                   1 non-null      object
 49  MULTI_DAMS                  0 non-null      object
 50  TIMELINE                    0 non-null      object
 51  COMMENTS                    0 non-null      object
 52  URL                         0 non-null      object
 53  QUALITY                     1 non-null      object
 54  EDITOR                      1 non-null      object
 55  LONG_DD                     1 non-null      float64
 56  LAT_DD                      1 non-null      float64
 57  POLY_SRC                    1 non-null      object
 58  ID_GRanD                    1 non-null      int64
 59  NL_Dam_Review_grand_Dam ID  1 non-null      object
 60  geometry                    1 non-null      geometry
dtypes: float64(13), geometry(1), int64(13), object(34)
memory usage: 616.0+ bytes

In [16]:
pr_humber_dams_nhn_df.head(2)

,OBJECTID,nid,validityDa,acquisitio,datasetNam,planimetri,provider,completely,manmadeTyp,manmadeT_1,...,name2,idDate,nameDate,SHAPE_Leng,SHAPE_Area,layer,path,ID_NHN,NL_Dam_Review_nhn_Dam ID,geometry
0,4249.0,a148a2e8c46446ba87d435f3e47c3dcb,1986,5,02YL000,10,2,1,1,Dam,...,None,None,None,0.000316,None,Point,"Point?crs=EPSG:4617&field=OBJECTID:long(0,0)&f...",3648,a148a2e8c46446ba87d435f3e47c3dcb,POINT (-57.03635 49.63076)
1,4248.0,f6550df191b0418da8367994f62e2c1d,1986,5,02YL000,17,2,1,1,Dam,...,None,None,None,0.000254,None,Point,"Point?crs=EPSG:4617&field=OBJECTID:long(0,0)&f...",3649,f6550df191b0418da8367994f62e2c1d,POINT (-58.08564 49.06965)

In [17]:
pr_humber_dams_nhn_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   OBJECTID                  31 non-null     float64
 1   nid                       31 non-null     object
 2   validityDa                31 non-null     object
 3   acquisitio                31 non-null     int64
 4   datasetNam                31 non-null     object
 5   planimetri                31 non-null     int64
 6   provider                  31 non-null     int64
 7   completely                31 non-null     int64
 8   manmadeTyp                31 non-null     int64
 9   manmadeT_1                31 non-null     object
 10  manmadeSta                31 non-null     int64
 11  geographic                0 non-null      object
 12  nameId1                   0 non-null      object
 13  nameId2                   0 non-null      object
 14  name1                     0 non-null      object
 15  name2                     0 non-null      object
 16  idDate                    0 non-null      object
 17  nameDate                  0 non-null      object
 18  SHAPE_Leng                20 non-null     float64
 19  SHAPE_Area                0 non-null      object
 20  layer                     31 non-null     object
 21  path                      31 non-null     object
 22  ID_NHN                    31 non-null     int64
 23  NL_Dam_Review_nhn_Dam ID  31 non-null     object
 24  geometry                  31 non-null     geometry
dtypes: float64(2), geometry(1), int64(7), object(15)
memory usage: 6.2+ KB

In [18]:
pr_humber_dams_nlprov_df.head(2)

,OBJECTID,LAT_DEC,LONG_DEC,DAMINDEXNUM,PROJECT_NAME,DAM_NAME,OWNER_NAME,YEARBUILT,DAMSTATUS,PURPOSE_DRINKING,...,PURPOSE_FLOOD,PURPOSE_ICE,PURPOSE_FORESTRY,PURPOSE_UNKNOWN,PURPOSE_OTHER,DAM_TYPE,DAM_TYPE_OTHER,DIM_MAXHEIGHT,NL_Dam_Review_nlprovince_Dam ID,geometry
0,944,49.008756,-57.561714,408,Pasadena Water Supply,Blue Gulch Brook West Dam,Town of Pasadena,None,Active,Primary,...,None,None,None,None,None,CAD = concrete arch,None,2.0,944,POINT (-57.56171 49.00876)
1,945,48.998247,-57.871769,409,Hughes Brook Water Supply,Water Supply Dam,Town of Hughes Brook,1986,Active,Primary,...,None,None,None,None,None,CGD = concrete gravity,None,3.0,945,POINT (-57.87177 48.99825)

In [19]:
pr_humber_dams_npdp_df

,NPDP_ID,CDA_ID,Dam Name,Alternative Dam Name,Dam Type,Dam Height (m),Dam Lengh (m),Hazard Class,Latitude,Longitude,...,Material,Dam Designer,Federal Regulatory Agency,Inspection Frequancy/ year,State Regulated,Mean Annual Energy,Electric Capacity,Source,NL_Dam_Review_npdp_Dam ID,geometry
0,787,97,Main Diversion D. Grand Lake,None,Buttress,25,226,Unknown,49.169952,-57.436113,...,None,None,None,None,None,None,None,None,787,POINT (-57.43661 49.17021)

In [20]:
pr_humber_falls_nhn_df.head()

,OBJECTID,nid,validityDate,acquisitionTechnique,datasetName,planimetricAccuracy,provider,completelyCover,obstacleType,obstacleTypeText,...,nameId1,nameId2,name1,name2,idDate,nameDate,SHAPE_Length,layer,path,geometry
0,149970,ea26c81b52ef4cddab421eca36c110ac,1986,5,02YL000,17,2,1,1,Falls,...,,,,,,,NaN,NHN_OB_0_falls,\\cwf-stge-svr4\share\Conservation Program\Fre...,POINT (-58.09071 48.94046)
1,149988,0d741e4c810a4402b0a4fb7d54f657a1,1986,5,02YL000,10,2,1,1,Falls,...,,,,,,,NaN,NHN_OB_0_falls,\\cwf-stge-svr4\share\Conservation Program\Fre...,POINT (-57.31074 49.52131)
2,150008,deb254892cfa44ed8bfbaa0fc097c987,1986,5,02YL000,10,2,1,1,Falls,...,,,,,,,NaN,NHN_OB_0_falls,\\cwf-stge-svr4\share\Conservation Program\Fre...,POINT (-57.17948 49.51085)
3,150031,2a4d97f612754fb3a253cab1340785ce,1986,5,02YL000,17,2,1,1,Falls,...,,,,,,,NaN,NHN_OB_0_falls,\\cwf-stge-svr4\share\Conservation Program\Fre...,POINT (-58.24835 49.01570)
4,150033,0f665eef639d4c6aa35ceeffe824cb84,1986,5,02YL000,10,2,1,1,Falls,...,,,,,,,NaN,NHN_OB_0_falls,\\cwf-stge-svr4\share\Conservation Program\Fre...,POINT (-57.90643 49.25651)

In [ ]:
pr_humber_falls_nhn_df.info()

- All barriers have latitude and longitude data as a point
- All but falls and dams_nhn have dam name
- The layer names can be used as the type for different types of barrier

# Prepare to export:
select only the important columns (location, type, ?) concatenate all and save as gpkg file

In [24]:
pr_humber_dams_grand_df['barrier_type'] = "grand"
pr_humber_dams_nhn_df['barrier_type'] = "nhn"
pr_humber_dams_nlprov_df['barrier_type'] = "nlprov"
pr_humber_dams_npdp_df['barrier_type'] = "npdp"
pr_humber_falls_nhn_df['barrier_type'] = "falls"

In [30]:
br_df_all_col = pd.concat([pr_humber_dams_grand_df, \
           pr_humber_dams_nhn_df, \
           pr_humber_dams_nlprov_df, \
           pr_humber_dams_npdp_df, \
           pr_humber_falls_nhn_df], axis=0)

br_df_all_col.to_file('data/Humber_Barriers_all_col.gpkg')

<ipython-input-30-c91af19959b7>:7: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  br_df_all_col.to_file('data/Humber_Barriers_all_col.gpkg')

In [27]:
br_df = pd.concat([pr_humber_dams_grand_df[['barrier_type', 'geometry']], \
           pr_humber_dams_nhn_df[['barrier_type', 'geometry']], \
           pr_humber_dams_nlprov_df[['barrier_type', 'geometry']], \
           pr_humber_dams_npdp_df[['barrier_type', 'geometry']], \
           pr_humber_falls_nhn_df[['barrier_type', 'geometry']]], axis=0)
br_df

   barrier_type                    geometry
0         grand  POINT (-57.25639 49.19823)
0           nhn  POINT (-57.03635 49.63076)
1           nhn  POINT (-58.08564 49.06965)
2           nhn  POINT (-57.81380 48.93041)
3           nhn  POINT (-57.07446 49.66377)
..          ...                         ...
26        falls  POINT (-57.43462 49.49406)
27        falls  POINT (-57.24249 49.64198)
28        falls  POINT (-57.63240 49.66568)
29        falls  POINT (-57.16961 49.34739)
30        falls  POINT (-57.17011 49.34712)

[98 rows x 2 columns]

In [63]:
br_df.to_file('data/Humber_Barriers.gpkg')